In [14]:
import numpy
from sklearn.datasets import load_breast_cancer 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.utils import to_categorical
from collections import Counter

In [47]:
def prediction(dados):
    dados = dados.reshape(1, -1)
    prediction = model.predict(dados)[0]
    malignant_prob = prediction[0] 
    benign_prob = prediction[1] 
    
    return f"There is {malignant_prob:.6f} probability of being malignant and {benign_prob:.6f} probability of being benign."


In [16]:
data = load_breast_cancer()
X = data.data
names = data.target_names
feature_names = data.feature_names
y = data.target

In [17]:
print(feature_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [18]:
print(X)
print(y)
print(data.DESCR)


[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [19]:
print(Counter(y))

Counter({1: 357, 0: 212})


In [20]:
Scaler = StandardScaler()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 60)

In [21]:
print(len(X_train))
print(len(y_train))
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)
y_train = to_categorical(y_train, num_classes=2)
y_test = to_categorical(y_test, num_classes=2)
print(X_train)

426
426
[[-0.86753284 -1.03462309 -0.84202873 ... -0.10775694  0.63455502
   0.36632785]
 [-0.19199165 -0.68960524 -0.22135893 ... -0.38247593 -1.33568306
  -0.41933703]
 [ 0.97192779  0.91967378  0.83645614 ... -0.49766567 -0.70042673
  -1.02157189]
 ...
 [-0.56339308 -0.36871453 -0.56249367 ... -0.80292621  0.23830602
  -0.71531409]
 [ 0.22035167  1.13199245  0.25869369 ...  0.72787249  0.66600335
   0.27488338]
 [ 0.31978197 -0.61963659  0.31731959 ...  0.16665198  0.81381052
   0.72344825]]


In [44]:
print(y_train)

[[0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 

In [22]:
checkpoint_callback = ModelCheckpoint(
    'best_model.keras',  monitor='accuracy',  save_best_only=True, save_weights_only=False,  verbose=1
)

"""
early_stopping_callback = EarlyStopping(
    monitor='val_loss', patience=10, restore_best_weights=True, verbose=1
)
"""
callbacks_list = [checkpoint_callback]

In [23]:
model = keras.Sequential([
    Dense(300, activation="relu"),
    keras.layers.Dropout(rate=0.2),
    Dense(300, activation='relu'),
    keras.layers.Dropout(rate=0.2),
    Dense(300, activation='relu'),
    keras.layers.Dropout(rate=0.2),
    Dense(2, activation='sigmoid'),
])

In [24]:
model.compile(optimizer="Nadam", loss = "binary_crossentropy", metrics = ['accuracy'])
history = model.fit(X_train,y_train, epochs= 20, callbacks= [callbacks_list])

Epoch 1/20
13/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8262 - loss: 0.5026 
Epoch 1: accuracy improved from -inf to 0.89671, saving model to best_model.keras
14/14 ━━━━━━━━━━━━━━━━━━━━ 5s 24ms/step - accuracy: 0.8356 - loss: 0.4840
Epoch 2/20
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9614 - loss: 0.1056
Epoch 2: accuracy improved from 0.89671 to 0.96714, saving model to best_model.keras
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9618 - loss: 0.1054
Epoch 3/20
10/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9700 - loss: 0.0720 
Epoch 3: accuracy improved from 0.96714 to 0.97183, saving model to best_model.keras
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9710 - loss: 0.0736
Epoch 4/20
 9/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9858 - loss: 0.0500 
Epoch 4: accuracy improved from 0.97183 to 0.97887, saving model to best_model.keras
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9829 - loss: 0.0524
Epoch 5/20
 5/14 ━━━━━━━━━━━

In [38]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)

print(f"Test Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_accuracy:.4%}")

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9946 - loss: 0.0358 
Test Loss: 0.0401
Test Accuracy: 99.3007%


In [49]:
print(y_test[1])

[0. 1.]


In [50]:
prediction(X_test[1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


'There is 0.456817 probability of being malignant and 0.560298 probability of being benign.'